language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

env:
  global:
    - TEST_DIR=/tmp/_altair_transform/

before_install:
  - pip install pip --upgrade;
  - pip install -r requirements_dev.txt
  - mkdir -p $TEST_DIR

install:
  - pip install .;

script:
  - black --check .
  - python -m flake8 altair_transform
  - python -m mypy altair_transform
  - cd $TEST_DIR && python -m pytest --pyargs altair_transform;