
# parser_Parser_parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEleftEXPrightUMINUSUPLUSDIVIDE EXP LPAREN MINUS NAME NUMBER PLUS RPAREN TIMESstatement : expression\n        expression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expression\n                  | expression EXP expression\n        expression : MINUS expression %prec UMINUSexpression : PLUS expression %prec UPLUSexpression : LPAREN expression RPARENexpression : NUMBERexpression : NAME'
    
_lr_action_items = {'MINUS':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,],[4,9,4,4,4,-10,-11,4,4,4,4,4,-8,-7,9,-2,-3,-4,-5,-6,-9,]),'PLUS':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,],[3,8,3,3,3,-10,-11,3,3,3,3,3,-8,-7,8,-2,-3,-4,-5,-6,-9,]),'LPAREN':([0,3,4,5,8,9,10,11,12,],[5,5,5,5,5,5,5,5,5,]),'NUMBER':([0,3,4,5,8,9,10,11,12,],[6,6,6,6,6,6,6,6,6,]),'NAME':([0,3,4,5,8,9,10,11,12,],[7,7,7,7,7,7,7,7,7,]),'$end':([1,2,6,7,13,14,16,17,18,19,20,21,],[0,-1,-10,-11,-8,-7,-2,-3,-4,-5,-6,-9,]),'TIMES':([2,6,7,13,14,15,16,17,18,19,20,21,],[10,-10,-11,-8,-7,10,10,10,-4,-5,-6,-9,]),'DIVIDE':([2,6,7,13,14,15,16,17,18,19,20,21,],[11,-10,-11,-8,-7,11,11,11,-4,-5,-6,-9,]),'EXP':([2,6,7,13,14,15,16,17,18,19,20,21,],[12,-10,-11,-8,-7,12,12,12,12,12,-6,-9,]),'RPAREN':([6,7,13,14,15,16,17,18,19,20,21,],[-10,-11,-8,-7,21,-2,-3,-4,-5,-6,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,3,4,5,8,9,10,11,12,],[2,13,14,15,16,17,18,19,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','parser.py',98),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','parser.py',103),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','parser.py',104),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','parser.py',105),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','parser.py',106),
  ('expression -> expression EXP expression','expression',3,'p_expression_binop','parser.py',107),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','parser.py',122),
  ('expression -> PLUS expression','expression',2,'p_expression_uplus','parser.py',126),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','parser.py',130),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',134),
  ('expression -> NAME','expression',1,'p_expression_name','parser.py',138),
]
