name: lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: flake8-black-mypy
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=10 --statistics
    - name: Check formatting with black
      run: |
        pip install black
        black --check .
    - name: Check types with mypy
      run: |
        pip install mypy
        mypy altair_transform
